### ISSUE TITLE
Dimension type VLR?

### ISSUE THREAD

**Issue by hobu** [copcio/copcio.github.io#20]
@m-schuetz's post https://github.com/copcio/copcio.github.io/issues/19#issuecomment-906755352 about desiring dimension type information brings up the question of whether it might be more generally useful.

My thought on the topic is COPC files are LAS/LAZ, and the dimension types and mappings of LAS files are generally known. Extra byte dimensions are rarer, and the type mapping of those dimensions is indeed missing. 

Can any reader client developers make a stronger case for this? @connormanning @CCInc ?

**Comment by abellgithub** [comment]
I don't understand this. The dimensions are well-known or types are provided in the EB VLR.

**Comment by CCInc** [comment]
I believe Andrew is correct, proper EB VLRs should define this (LAS 1.4 spec p 25)

**Comment by hobu** [comment]
None of the EB VLRs tell you what type of data it is (enumeration, continuous or discrete). As a client, you often need that or have to scan to get that yourself.

**Comment by abellgithub** [comment]
The term "data type" is confusing here. Perhaps "data interpretation"?

I don't understand Markus' linked comment.

**Comment by hobu** [comment]
> The term "data type" is confusing here. Perhaps "data interpretation"?

ok, how about "kind"? A data field's "kind" might be enumeration, continuous or discrete.

> I don't understand Markus' linked comment.

I believe Markus is asking for a way for a writer to hint a renderer with a dimension's kind to make it easier for the renderer to compose the rendering. In addition to the kind, he's proposing to have the data embed rendering transforms.

**Comment by abellgithub** [comment]
What is continuous vs. discrete? The only places that I would think this would come up is with enumerations like classification and cluster ID. I really don't see this being used much and it probably belongs in the LAS standard rather than the COPC doc. I would think that a GUI would know that classification and cluster ID are enumerations without being told.  I have a hard time believing that people creating these files are going to do anything other than roll up existing LAS/LAZ files, which don't contain this information.

**Comment by hobu** [comment]
I hope @m-schuetz and other renderer developers can expand on this more, or this thread is dead.
