### ISSUE TITLE
Lock Version 1.0.0

### ISSUE THREAD

**Issue by timodwhit** [copcio/copcio.github.io#41]
Are we at a point where we can lock the spec for v1.0.0? 

All issues are resolved here (sans new example file). If we cut the 1.0.0 version, then other libs would be able to fully implement the spec and ensure future changes.

**Comment by abellgithub** [comment]
I would say that goal here is to have something that we don't have to change. Without sufficient use and testing, we can't be sure that the specification meets the needs of potential users. A changing specification does nobody any good.

Nobody's stopping you from going forward and you should probably do that in order to help make sure that things haven't been missed. Many of the changes that we've made in the specification have come from finding issues when actually trying to use the spec. for real data. We've made meaningful changes in the last week or so. I hope we're done. but it's going to take more data and use to make sure that it is complete and useful as is.

**Comment by timodwhit** [comment]
Agreed, but without sometime of locked version alpha, beta, etc. it is hard to write and maintain software that is usable, upgradable, lockable for that sufficient use and testing in the wild.

**Comment by abellgithub** [comment]
I'll note that the specification says "Copyright Hobu Inc.". We're developing this in the open and are happy to receive input from you and others, but it's done when we're comfortable that the likelihood that we've missed anything meaningful is very low.

Hobu Inc. would also would like to remove the "draft" status, but it's pointless unless we actually mean it.

Calling it done when it's not done doesn't help anyone maintain software. I can speak from personal experience on this WRT LAS. They're on revision *15* of the 1.4 specification. To which of these 15 revisions does your software conform? Or your files?

**Comment by abellgithub** [comment]
Unless that *documentation* change is married with a *file* change, you just have a mess, which is exactly what LAS is facing. Rock Robotics can tag its software with anything it likes. Put a UUID of the COPC spec rev in there if you want. But I don't see any value to users unless you can say with certainty "your file conforms with version 1.0". What are they to do if it conforms to version 1.0beta1 but not version 1.0?

As I said, I have faced *exactly* this issue with LAS. Neither the software nor the user knows what's correct, because they're all correct -- according to some version of the document.

**Comment by timodwhit** [comment]
> Unless that documentation change is married with a file change

Under what scenario would this not be the case for this repo?

> Rock Robotics can tag its software with anything it likes

This is about all the software that is used. While I work at RR, and we do have a vested interest in this format, there are a lot of softwares that do and we want to help those and make sure all of the tooling has a stable path forward for releasing when v1.0.0 release.

> What are they to do if it conforms to version 1.0beta1 but not version 1.0?

Betas carry no guarantee, but knowing what version a software and ancillary tooling is on is helpful to see a path. However, holding for the solid version delays the release and stability of all those projects that look to implement the path. I get that Las/LAZ has been more than challenging, we also see where many many many softwares have released beta versions of apis/specs successfully.

Betas are not meant to be in the wild, but asking for "sufficient use and testing" with a constantly moving target takes a large investment in time and rewrites, etc.

**Comment by timodwhit** [comment]
@abellgithub Thank you for your opinion.

We appreciate the discussion and the clarity into the process and the decisions that have been made. If you are aware of other organizations that are actively working on COPC lib, I recommend you point them to this discussion and your recommendations. We will do the same. 

Also, we hope to not come off as pushy, we are simply trying to provide a usable stable product for the community (albeit small) and help to provide feedback where we see fit.

**Comment by hobu** [comment]
See #52
