### ISSUE TITLE
Remaining TODOs

### ISSUE THREAD

**Issue by timodwhit** [copcio/copcio.github.io#6]
We (rockrobotic) would love to help on getting the spec and work finalized. Would it be helpful to use the issue queue and assignees or just a task list here?

**Comment by timodwhit** [comment]
@hobu we are definitely willing to help with ancillary projects like potree and currently have the work in our backlog. We are also currently looking at writing a pdal reader as well.

First we want to get the spec finalized and would love to help with that or any remaining work to make sure this crosses the line so those ancillary projects don't require re-work.

**Comment by timodwhit** [comment]
Issue created on potree to track progress: https://github.com/potree/potree/issues/1065

**Comment by CCInc** [comment]
@hobu laz-perf does not support LAZ 1.4 as far as I understand. So, for the EPT reader I developed in potree (unpublished) I used the https://github.com/laz-rs/laz-rs-wasm library. We will probably use that library for the COPC support as well.

**Comment by hobu** [comment]
> @hobu laz-perf does not support LAZ 1.4 as far as I understand. 

@abellgithub just put a whole bunch of work into laz-perf to add it.

**Comment by midnight-dev** [comment]
Only briefly read about the concept, so apologies if I missed something. If laz-perf handles the LAZ 1.4 decoding, then that leaves the handling of decompressed data up to potree. Can most of the existing EPT potree backend be used for this new format? That would be a bit of a blessing. Not awfully familiar with LAS 1.4 other than always using it during post processing. Does it contain a mechanism for including entwine-esque point data? Just trying to wrap my head around how the extra data is packaged with the LAZ.

By the way, what program(s) can create or convert to COPC?

**Comment by m-schuetz** [comment]
When working on support for Potree, try to make it as self-contained as possible. I'm currently working on a WebGPU-based rewrite (Potree 2.0) that could be considered an entirely different project, so would be nice if it could be easily adapted in the future.

**Comment by hobu** [comment]
> When working on support for Potree, try to make it as self-contained as possible

Can you provide links to any guidance on how exactly one might do that?

**Comment by m-schuetz** [comment]
Essentially I'm thinking that it would be great if a copc loader would be a library that any JS application could easily integrate. With an API that exposes functions that return the hierarchy, perhaps incrementally/recursively if it is large, and functions that return decompressed array buffers for a given node.

**Comment by CCInc** [comment]
I was going to create both a JS library and a python library that does what you're describing so that it can be easily integrated in multiple applications.

**Comment by CCInc** [comment]
@hobu @m-schuetz What would be your thoughts about me creating a generic C++ library to implement those features (reading metadata, getting a chunk by xyz, etc), which we could then write wrappers for and use in PDAL, potree, and python?

It seems like that might be the easiest way to avoid code duplication and ensure cross compatibility.

**Comment by evetion** [comment]
Could the native laszip shared library (and the exposed c/c++ API) work with a (file-based) COPC? I'm not sure how the variably-chunked data would work with it.

I'm the author of https://github.com/evetion/LazIO.jl, which uses the laszip library. I can imagine many others use/extend the same API. I would be open to switching/contributing to a COPC C++ implementation as proposed by @CCInc.

**Comment by abellgithub** [comment]
@evetion A file COPC is a LAZ file, so can be read using lastools. However, I don't believe that the laszip API has an interface to decode an individual compressed chunk of data. Certainly, all the code is there to do the job, but I don't believe that there's a function that handles that case -- it expects a complete LAZ file with a header and chunk table. You could coerce a chunk of data into a "file" and then use `laszip_open_reader_stream` -- not trivial, but not awful. The [lazperf](https://github.com/hobu/laz-perf) library does support this use case.

**Comment by CCInc** [comment]
@evetion @abellgithub I'll be releasing the first iteration of my library later today for you to take a look at.

If you could let me know what library functions you would find useful that'd be very helpful. Right now, the only function I publicly expose is one that gives you decompressed point data given a VoxelKey. I'll also eventually add functions that let you get point data given coordinates and bounds, similar to how PDAL does. If you have any other ideas please let me know.

Currently, I'm just returning the point data as a byte array. If you think it'd be within the scope of this library I could add point type structures and return arrays of points. This might be helpful in python especially, for users who want a laspy-like experience.

**Comment by connormanning** [comment]
Hey all, I've made public my work-in-progress TypeScript COPC library [here](https://github.com/connormanning/copc.js).  At the moment, it parses the LAS (header/VLRs/EVLRs) and COPC (offsets, hierarchy) metadata, and allows you to read point data.  The hierarchy is lazily loaded as needed, and you can grab point data via generic getter functions with a [point view style](https://github.com/connormanning/copc.js/blob/master/src/copc/copc.test.ts#L8-L10), or you can walk the underlying hierarchy [manually](https://github.com/connormanning/copc.js/blob/master/src/copc/hierarchy.test.ts#L11-L17) and decompress your LAS point data buffers as necessary (via updated WASM build from laz-perf).  Remote storage (HTTP/S3/Dropbox) is supported out of the box, and a custom range getter function can be passed anywhere you see a `filename` for a user-provided IO layer.

The COPC data structure looks like [this](https://gist.github.com/connormanning/b3793229c062adc29ae4efcb57764412).

Some immediate TODOs are:
- Better testing - there are decent unit tests but they are "snapshot" tests from a sample file to aid my development rather than good isolated test cases
- CLI tools: `copc info` and `copc validate`, maybe others
- Fill out the API footprint, for example `Hierarchy.loadAll` and other useful utilities
- Extra bytes dimension support

My current next step is to integrate this into [EPT Tools](https://github.com/connormanning/ept-tools) for visualization purposes, which will probably expand the API a bit after which point it would be suitable for integration into Potree.

Regarding @CCInc :
> @hobu @m-schuetz What would be your thoughts about me creating a generic C++ library to implement those features (reading metadata, getting a chunk by xyz, etc), which we could then write wrappers for and use in PDAL, potree, and python?

I'd be curious to see how a JS wrapper of your C++ library would look, but I tend to think the way you would want to access things looks different in JS than in C++.  I have a feeling that a natively written copc.js will be more pleasant to work with in JS (not to mention the TS support) than an equivalent wrapped C++ library - but I'm happy to be proven wrong.

**Comment by CCInc** [comment]
We've also gone public with our first release of our library [copc-lib](https://github.com/RockRobotic/copc-lib). Please let us know some feedback about what other features you'd like to see. Similarly to Connor's library, our library parses the LAS headers/vlrs and COPC struct upon opening a file. Within our library, you can request individual nodes given a `VoxelKey`. The hierarchy is lazily loaded as needed. You can get the  decompressed point data of a node given a `VoxelKey` as a `vector<char>` (i.e. a `char*` buf).

Currently on our TODO list:
- Returning point structs in addition to a raw char* array.
- Adding writer functionality
- Spatial querying for nodes
- Python bindings

Our immediate goal is to integrate copc-lib into both CopcConverter and PDAL, with the other TODOs coming after (since CopcConverter and PDAL already have the ability to parse LAS point bytes into their own format).

@connormanning Regarding the JS library, my aim with this project was to have a consolidated tool to use anywhere COPC needed to be read or written to avoid the situation we have with the LAZ format, with laz-perf, laz-rs, and laszip all having different APIs and functionaries, with each only applicable to some use cases (although laz-perf has been the easiest one to use by far). However, that shouldn't be a big issue here since the JS environment is so different than C++/python, plus we are both committed to following spec. Figuring out emscripten will probably be more trouble than it's worth, and you're right that cross-compiled C++ is not fun to work with from the JS perspective.

So, I think our best approach would be for us to help maintain the JS lib and you can help with copc-lib, and together we can ensure our implementations stay consistent. How does that sound?

**Comment by connormanning** [comment]
Sounds good to me.  As a quick note, I question the point "Returning point structs in addition to a raw char* array" in relation to its interaction with extra bytes (I think some more generic point-view or getter-function type of thing may be better) - but that's a discussion for another place.

Going to close this issue since I think the remaining tasks have largely been portioned out and are under active development at this point.

**Comment by CCInc** [comment]
Hi all, Leo and I just finished adding Writer support to copc-lib (https://github.com/RockRobotic/copc-lib). It will allow you to create new COPC files without using any other LAS/LAZ libraries. It supports all of the COPC spec, and allows you to add points via a Point object class, the compressed point data and uncompressed data. Python bindings for all this will be coming soon. Let me know what you think!
